#!/bin/bash
set -e

status() {
    if pgrep -f i3-autotile > /dev/null; then
        echo "[]="
    else
        echo ""
    fi
}


toggle() {
if pgrep -f i3-autotile > /dev/null; then
   notify-send -a sysnfo_notify-l 'Autotiling disabled!'
   pkill -f i3-autotile
   pkill -SIGRTMIN+7 waybar
else
    ~/.local/bin/i3-autotile &
   notify-send -a sysnfo_notify-l '[]= Autotiling enabled!'
   pkill -SIGRTMIN+7 waybar
fi
}


case "$1" in
    "status")
        status
        ;;
    "toggle")
        toggle
        ;;
    *)
        echo "Invalid argument"
        exit 1
        ;;
esac

