#!/bin/bash
set -e

status() {
    if pgrep -f i3-autotile > /dev/null; then
        echo "󰄹"
    else
        echo ""
    fi
}


toggle() {
if pgrep -f i3-autotile > /dev/null; then
    pkill -f i3-autotile
   notify-send -a sysnfo_notify-l ' autotiling disabled!'
else
   notify-send -a sysnfo_notify-l '󰄹 autotiling enabled!'
   ~/.local/bin/i3-autotile
fi
pkill -SIGRTMIN+7 waybar
}


case "$1" in
    "status")
        status
        ;;
    "toggle")
        toggle
        ;;
    *)
        echo "Invalid argument"
        exit 1
        ;;
esac

