#!/usr/bin/env bash
#
# This small script shows system info with libnotify
# check your sensors and edit grep value according to your temp sensor

CPUTemp=$(sensors | grep 'Tctl:' | awk '{print $2}' )
CPUTemp2=$(sensors | grep 'Tccd1:' | awk '{print $2}' )
GPUTemp=$(sensors | grep 'edge:' | awk '{print $2}' )
upt="$(uptime --pretty | sed -e 's/up //g' -e 's/ days/d/g' -e 's/ day/d/g' -e 's/ hours/h/g' -e 's/ hour/h/g' -e 's/ minutes/m/g' -e 's/, / /g')"
kernel=$(uname -r)
notify-send -t 8000 "$(
printf "Kernel: $kernel\n"
free -m | awk 'NR==2{printf "Ram: %s/%sMB\n", $3,$2,$3*100/$2 }'
top -bn1 | grep load | awk '{printf "Load: %.2f\n", $(NF-2)}'
df -h / | awk 'FNR==2 { gsub(/[A-Za-z]/, ""); printf "Free: %i GiB \n", $4 }'
printf "CPU Tctl: $CPUTemp\n"
printf "CPU Tccd1: $CPUTemp2\n"
printf "GPU temp: $GPUTemp\n"
printf "Up:$upt"
)"

