#!/bin/bash

set -euo pipefail

pactl set-source-mute @DEFAULT_SOURCE@ toggle
if pactl list sources | grep -q "Mute: yes"; then
    notify-send -a vol_notify "Mic" "off" -h string:x-canonical-private-synchronous:volume
else
    notify-send -a vol_notify  "Mic" "on" -h string:x-canonical-private-synchronous:volume
fi
