#!/usr/bin/env bash

# rofi theme
THEME="$HOME/.config/rofi/rofi_screenshot/theme.rasi"

get_options() {
  echo "  Record Screen (MP4)"
  echo "  Record Region (MP4)"
  echo "  Screenshot Full"
  echo "  Screenshot Region"
  echo "  Screenshot Full+delay"
  echo "  Stop Recording"
}

main() {

  # Get choice from rofi
  choice=$( (get_options) | rofi -dmenu -i -fuzzy -p "Capture" -theme "$THEME")

  # If user has not picked anything, exit
  if [[ -z "${choice// /}" ]]; then
    exit 1
  fi

  # run the selected command
  case $choice in
  '  Record Screen (MP4)')
    sway-record -f
    ;;
   '  Record Region (MP4)')
    sway-record -r
    ;;
   '  Screenshot Full' )
    sway-shot -f
    ;;
  '  Screenshot Region')
    sway-shot -r
    ;;
   '  Screenshot Full+delay')
    sway-shot -d
    ;;
  '  Stop Recording')
    sway-record -k
    ;;
  esac

  # done
  set -e
}

main &

exit 0
