#!/usr/bin/env bash
dir="$HOME/.config/rofi/"
theme='rofi_powermenu'
prompt=$(uptime -p | sed 's/up/Uptime:/;s/ days\?/d/;s/ hours\?/h/;
    s/ minutes\?/m/;s/,//g')

shutdown=' Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend=' Suspend'
logout=' Logout'
yes='Yes'
no='No'

rofi_cmd() {
	rofi -dmenu -i\
		-p "${prompt}"\
		-theme ${dir}/${theme}.rasi
}

confirm_cmd() {
	rofi 	-dmenu -i \
		-p 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			systemctl reboot
		fi
	else
		exit 0
	fi
}

chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
	    swaylock
        ;;
    $suspend)
		systemctl suspend
        ;;
    $logout)
	    swaymsg exit	
        ;;
esac

