#!/bin/bash

# Menu options
ARCHIVE="SWAY
FOOT
TOFI
WAYBAR
SWAYLOCK
ZSH
NEOVIM
GTK-SETTINGS
MAKO"
CHOICE=$(printf "$ARCHIVE" | tofi --text-cursor false \
    --margin-top 2 \
    --exclusive-zone 0 \
    --anchor top \
    --font-size 10 \
    --prompt-text "Edit settings: " \
    --height 300 \
    --width 100% )

# Launch nvim on with foot as floating window
TERMCMD=("foot -a floatterm")

case $CHOICE in
     SWAY) $TERMCMD -e nvim $HOME/.config/sway/config ;;
     FOOT) $TERMCMD -e nvim $HOME/.config/foot/foot.ini ;;
     TOFI) $TERMCMD -e nvim $HOME/.config/tofi ;;
     WAYBAR) $TERMCMD -e nvim $HOME/.config/waybar ;;
     SWAYLOCK) $TERMCMD -e nvim $HOME/.config/swaylock/config ;;
     NEOVIM) $TERMCMD -e nvim $HOME/.config/nvim ;;
     GTK-SETTINGS) nwg-look ;;
     MAKO) $TERMCMD -e nvim $HOME/.config/mako ;;
     ZSH) $TERMCMD -e nvim $HOME/.config/zsh/.zshrc ;;
esac


