#!/bin/sh

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/lf"
mkdir -p "$CACHE_DIR"

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
    chafa -f sixel -s "$2x$3" --animate off --polite on "$1" | sed 's/#/\n#/g'
}

case "$(file --dereference --brief --mime-type -- "$1")" in
    image/*) image "$1" "$2" "$3" "$4" "$5" "$1"
        ;;
    text/html) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" 
        ;;
    text/troff) man ./ "$1" | col -b 
        ;;
    text/* | */xml | application/json | application/x-ndjson) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" 
        ;;
    video/* )
        CACHE="${CACHE_DIR}/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
        [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
        image "$CACHE" "$2" "$3" "$4" "$5" "$1"
        ;;
    */pdf)
        CACHE="${CACHE_DIR}/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
        [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;
    application/*zip) atool --list -- "$1" 
        ;;
    *opendocument*) odt2txt "$1" 
        ;;
esac
exit 0

