#!/usr/bin/env bash
# https://github.com/bitterhalt
set -e

cliphist list | tofi  --text-cursor false \
    --font-size 12 \
    --prompt-text "Clipboard:" \
    --selection-color 101419 \
    --selection-background BF68D9 \
    --selection-background-padding "0, 6" \
    --padding-left  10 \
    --padding-top  10 \
    --width 100% \
    --height 40% \
    --anchor top \
    --corner-radius 0 \
    --border-width 0 | \
    cliphist decode | wl-copy
