#!/usr/bin/env bash
#
set -e

get_options() {
  echo "  Record Screen (MP4)"
  echo "  Record Region (MP4)"
  echo "  Screenshot Full"
  echo "  Screenshot Region"
  echo "  Screenshot Full+delay"
  echo "  Stop Recording"
}

main() {

    choice=$( (get_options) | tofi --width 320 \
        --height 310 \
        --padding-top 30 \
        --padding-left 20 \
        --result-spacing 8 \
        --prompt-text "" \
        --placeholder-text "Tofi screenhot" \
        --font-size 14)

  if [[ -z "${choice// /}" ]]; then
    exit 1
  fi

  case $choice in
  '  Record Screen (MP4)')
    sway-record -f
    ;;
   '  Record Region (MP4)')
    sway-record -r
    ;;
   '  Screenshot Full' )
    sway-shot -f
    ;;
  '  Screenshot Region')
    sway-shot -r
    ;;
   '  Screenshot Full+delay')
    sway-shot -t
    ;;
  '  Stop Recording')
    sway-record -k
    ;;
  esac
}

main &

exit 0
