#!/usr/bin/env bash
set -e
case "$1" in
    wipe)
        answer=$(echo -e "Yes\nNo" | tofi --text-cursor false \
            --anchor top \
            --font-size 10 \
            --prompt-text "Wipe Clipboard?" \
            --width 100% \
            --height 120)

        if [[ $answer == "Yes" ]]; then
            rm $XDG_CACHE_HOME/cliphist/db
            notify-send -a center_notify "Clipboard" "Database deleted"
        fi

        exit 0
        ;;
    *)
        cliphist list | tofi --text-cursor false \
            --anchor top \
            --font-size 10 \
            --prompt-text "Clipboard? " \
            --height 230 \
            --width 100% | cliphist decode | wl-copy
    esac
