#!/usr/bin/env bash
# https://github.com/bitterhalt
set -e

cliphist list | tofi  --text-cursor false \
    --font-size 14 \
    --prompt-text "" \
    --placeholder-text "Clipboard:"\
    --width 20% \
    --height 40% \
    --anchor center \
    --corner-radius 0 \
    --border-width 1 | \
    cliphist decode | wl-copy
