#!/bin/bash
# https://github.com/bitterhalt
set -euo pipefail

CONFIRM="tofi --text-cursor false \
        --border-width 0 \
        --font-size 34 \
        --prompt-text "Sure?" \
        --width 100% \
        --prompt-color 8f8f8f \
        --text-color 8f8f8f \
        --background-color 000D \
        --height  100% \
        --padding-left  45% \
        --hide-cursor true \
        --padding-top  40%"

case $(printf "%s\n" "Lock"  "Logout" "Suspend" "Reboot" "Shutdown" | tofi --font-size 34 \
    --border-width 0 \
    --outline-width  0 \
    --background-color 000D \
    --text-color 8f8f8f \
    --selection-background-corner-radius 8 \
    --selection-background-padding "4, 20" \
    --prompt-text  " " \
    --result-spacing  10 \
    --width 100% \
    --height  100% \
    --padding-left  45% \
    --padding-top  35% \
    --hide-input  false \
    --hide-cursor true) in
 "Shutdown")
    confirm=$(echo -e "Yes\nNo" | $CONFIRM )
    if [[ "$confirm" == "Yes" ]]; then
        systemctl poweroff
    fi
    ;;
"Reboot")
    confirm=$(echo -e "Yes\nNo" | $CONFIRM )
    if [[ "$confirm" == "Yes" ]]; then
        systemctl reboot
    fi
    ;;
"Suspend")
    systemctl suspend
    ;;
"Lock")
    $HOME/.config/sway/scripts/screenlocker
    ;;
"Logout")
    swaymsg exit
    ;;
esac
