#!/usr/bin/env bash
# https://github.com/bitterhalt

set -e

tofi-drun --prompt-text  " drun:"\
   --min-input-width 120 \
   --num-results  15 \
   --drun-launch=true \
   --font-size  14  \
   --anchor  top \
   --border-width  0 \
   --height  30 \
   --horizontal  true \
   --outline-width  0 \
   --padding-bottom  0 \
   --padding-left 0 \
   --padding-right  0 \
   --padding-top  2 \
   --prompt-padding  10 \
   --result-spacing  15 \
   --width  100% 

