#!/usr/bin/env bash
# https://github.com/bitterhalt
set -e

selected="$(ps -a -u $USER | \
    tofi  --text-cursor false \
    --font-size 13 \
    --prompt-text "Kill process:" \
    --width 30% \
    --height 45% \
    --padding-bottom 20 \
    --anchor center \
    --corner-radius 0 \
    --border-width 2  |
    awk '{print $1" "$4}')"

# confirm window
if [[ ! -z $selected ]]; then
    answer="$(echo -e "yes\nno" |
        tofi  --prompt-text "Delete Clipboard?" \
            --height   12% \
            --border-width  2 \
            --outline-width  1 \
            --padding-left  20)"

    if [[ $answer == "yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"
        kill -9 $selpid
    fi
fi

exit 0

