#!/bin/sh

##########
# Starters
##########
riverctl spawn "~/.config/river/scripts/autostart.sh"
riverctl spawn "dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY"



term="footclient"
drun="j4-dmenu-desktop --dmenu='bemenu_runner -B1 -n -l10 -p drun:'"
run="bemenu_runner run --no-exec -B1 -n -p "run:" -l10  | xargs riverctl spawn >/dev/null 2>&1"
########
# Launch
########
riverctl map normal Super D spawn "$drun"
riverctl map normal Super P spawn "$run"
riverctl map normal Super+Shift p spawn "bemenu_power"
riverctl map normal Super Return spawn "$term"
riverctl map normal Super F1 spawn "noti_sysnfo"
riverctl map normal Super F2 spawn "noti_usage cpu"
riverctl map normal Super F3 spawn "noti_usage ram"
riverctl map normal Super F4 spawn "bemenu_killer"
riverctl map normal Super F7 spawn "bemenu_screenshot"
riverctl map normal Super F9 spawn "~/.config/river/scripts/mic-toggle.sh && pkill -RTMIN+2 waybar"
riverctl map normal Super F11 spawn "~/.config/river/scripts/locker.sh"
riverctl map normal Super+Shift F11 spawn "~/.config/river/scripts/swayidle-toggle.sh && pkill -RTMIN+3 waybar"
riverctl map normal Super W spawn "firefox"
riverctl map normal Super e spawn "thunar"
riverctl map normal Super m spawn "thunderbird"
riverctl map normal Super Print spawn "sway-shot -f"
riverctl map normal Super+Shift Print spawn "sway-shot -re"
riverctl map normal Super+Control P spawn "colorpicker_fancy"
riverctl map normal Super+Control W spawn "noti_weather"
riverctl map normal Super+Control T spawn "noti_date"
riverctl map normal Super N spawn "foot -e nvim ~/Documents/personal/notes/index.md"
riverctl map normal Super+Shift N spawn "foot -a quick_note -e ~/.local/bin/quick_note"
riverctl map normal Super T spawn "foot -a floatterm -e nvim ~/Documents/personal/notes/todo.md"
riverctl map normal Super+Shift Delete spawn "$term -a floatterm -e htop"
riverctl map normal Super+Shift C spawn "bemenu_clipboard"
riverctl map normal Super+Control C spawn "bemenu_clipboard wipe"
riverctl map normal Super F12 spawn "dot-settings"
############
# River binds
#############
# Super+Q to close the focused view
riverctl map normal Super Q close

# Reload config
riverctl map normal Super+Control R spawn "$HOME/.config/river/init && notify-send -a center_notify 'River' 'Config reloaded'"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+z or (BackSpace) to bump the focused view to the top of the layout stack
riverctl map normal Super z zoom
riverctl map normal Super BackSpace zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+Prior and Super+Shift+Next to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift Prior send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift Next send-layout-cmd rivertile "main-count -1"

# Super+Control+{H,J,K,L} to move views
riverctl map normal Super+Control Left move left 100
riverctl map normal Super+Control Down move down 100
riverctl map normal Super+Control Up move up 100
riverctl map normal Super+Control Right move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
#riverctl map normal Super+Alt+Control H snap left
#riverctl map normal Super+Alt+Control J snap down
#riverctl map normal Super+Alt+Control K snap up
#riverctl map normal Super+Alt+Control L snap right

# Super+Shift+arrows to resize views
riverctl map normal Super+Alt Left resize horizontal -100
riverctl map normal Super+Alt Down resize vertical 100
riverctl map normal Super+Alt Up resize vertical -100
riverctl map normal Super+Alt Right resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Use cursed arrow keys: Super+Alt{F10,F12,F11,F9} to change layout orientation
riverctl map normal Super+Alt F10    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt F12 send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt F11  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt F9  send-layout-cmd rivertile "main-location left"


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
riverctl map $mode None XF86AudioRaiseVolume  spawn "~/.config/river/scripts/volume-thing.sh up"
riverctl map $mode None XF86AudioLowerVolume  spawn "~/.config/river/scripts/volume-thing.sh down"
riverctl map $mode None XF86AudioMute         spawn "~/.config/river/scripts/volume-thing.sh mute"
riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
riverctl map $mode None XF86AudioNext  spawn "playerctl next"
riverctl map $mode None XF86Calculator spawn "galculator"
done

########
# Colors
# ######
riverctl background-color 0x000000
riverctl border-color-focused 0xAA759F
riverctl border-color-unfocused 0x262626
riverctl border-width 1

########
# Inputs
########
#riverctl set-repeat 50 300
riverctl keyboard-layout "fi"
riverctl focus-follows-cursor normal
riverctl input pointer-9610-54-Glorious_Model_O accel-profile flat
riverctl input pointer-9610-54-Glorious_Model_O pointer-accel 0

######
#Rules
######

# Tags
riverctl rule-add -app-id "Thunderbird" tags $((1 << (3 - 1)))
riverctl rule-add -app-id "Firefox" tags $((1 << (2 - 1)))
riverctl rule-add -app-id "steam" tags $((1 << (5 - 1)))
riverctl rule-add -app-id "org.keepassxc.KeePassXC" tags $((1 << (3 - 1)))

# Floaters
riverctl rule-add -app-id "Firefox" -title "Picture-in-Picture" float
riverctl rule-add -app-id "KeePassXC" -title "Passkey credentials" float
riverctl rule-add -app-id "KeePassXC" -title "Browser Access Request" float
riverctl rule-add -app-id "GParted" float
riverctl rule-add -app-id "blueman-manager" float
riverctl rule-add -app-id "galculator"  float
riverctl rule-add -app-id "imv" float
riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "nwg-look" float
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float
riverctl rule-add -app-id "xdg-desktop-portal-gtk" float
riverctl rule-add -title "gtk*" float
riverctl rule-add -app-id "floatterm" float
riverctl rule-add -app-id "steam" float

# decorations

# This tries to force server side decorations. You can override this per.app by using "csd" rule below
riverctl rule-add ssd

riverctl rule-add -app-id "steam" csd

# Set the default layout generator to be rivertile and start it.
riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 0 &
