#!/usr/bin/env bash
# https://github.com/bitterhalt
# Note: Yes you see numbers before results
# Read: https://github.com/sentriz/cliphist#faq and https://github.com/philj56/tofi/issues/102

set -e

list () {
    cliphist list | fuzzel -d -p "Cliphist " -l 17 -w 60 --log-level error |
        cliphist decode | wl-copy
    }

    wipe () {
        answer="$(echo -e "Yes\nNo" |
            fuzzel -d -l 2 -w 20 -p "Wipe Clipboard? " )"

        if [[ $answer == "Yes" ]]; then
            rm $XDG_CACHE_HOME/cliphist/db
            notify-send "Clipboard database deleted!"
        fi
        exit 0
    }

    case "$1" in 
        "-l")
            list
            ;;
        "-w")
            wipe
            ;;
        *)
            echo "Invalid argument"
            exit 1
            ;;
    esac
