#!/usr/bin/env bash

get_options() {
  echo "  Record Screen (MP4)"
  echo "  Record Region (MP4)"
  echo "  Screenshot Full"
  echo "  Screenshot Region"
  echo "  Screenshot Full+delay"
  echo "  Stop Recording"
}

main() {

    choice=$( (get_options) | fuzzel -d  -f "Jetbrains Mono:size=16" --line-height=35 -w 25 -l 5 -p "Screenshot menu " --log-level error)

  if [[ -z "${choice// /}" ]]; then
    exit 1
  fi

  case $choice in
  '  Record Screen (MP4)')
    sway-record -f
    ;;
   '  Record Region (MP4)')
    sway-record -r
    ;;
   '  Screenshot Full' )
    sway-shot -f
    ;;
  '  Screenshot Region')
    sway-shot -r
    ;;
   '  Screenshot Full+delay')
    sway-shot -t
    ;;
  '  Stop Recording')
    sway-record -k
    ;;
  esac

  set -e
}

main &

exit 0
